// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Mirror of `CBManagerState`.
enum BleAdapterState {
  unknown,
  resetting,
  unsupported,
  unauthorized,
  poweredOff,
  poweredOn,
}

/// Lifecycle of a single peer link.
enum PeerConnectionState {
  disconnected,
  connecting,
  connected,
  disconnecting,
}

/// One-time configuration handed to the native transport on startup.
class TransportConfig {
  TransportConfig({
    required this.serviceUuid,
    required this.characteristicUuid,
    required this.displayName,
    required this.centralRestoreIdentifier,
    required this.peripheralRestoreIdentifier,
  });

  /// Custom 128-bit GATT service UUID advertised + scanned for.
  String serviceUuid;

  /// Single bidirectional write/notify characteristic UUID.
  String characteristicUuid;

  /// Short name surfaced to the peer in the hello/identity handshake.
  String displayName;

  /// `CBCentralManagerOptionRestoreIdentifierKey` value.
  String centralRestoreIdentifier;

  /// `CBPeripheralManagerOptionRestoreIdentifierKey` value.
  String peripheralRestoreIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      serviceUuid,
      characteristicUuid,
      displayName,
      centralRestoreIdentifier,
      peripheralRestoreIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static TransportConfig decode(Object result) {
    result as List<Object?>;
    return TransportConfig(
      serviceUuid: result[0]! as String,
      characteristicUuid: result[1]! as String,
      displayName: result[2]! as String,
      centralRestoreIdentifier: result[3]! as String,
      peripheralRestoreIdentifier: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TransportConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(serviceUuid, other.serviceUuid) && _deepEquals(characteristicUuid, other.characteristicUuid) && _deepEquals(displayName, other.displayName) && _deepEquals(centralRestoreIdentifier, other.centralRestoreIdentifier) && _deepEquals(peripheralRestoreIdentifier, other.peripheralRestoreIdentifier);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A peer surfaced by a scan match.
class PeerInfo {
  PeerInfo({
    required this.peerId,
    this.name,
    required this.rssi,
  });

  /// Stable opaque identifier for the discovered peripheral (CBPeripheral
  /// identifier UUID string). Not the cryptographic identity — that arrives
  /// inside the first signed envelope.
  String peerId;

  String? name;

  int rssi;

  List<Object?> _toList() {
    return <Object?>[
      peerId,
      name,
      rssi,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeerInfo decode(Object result) {
    result as List<Object?>;
    return PeerInfo(
      peerId: result[0]! as String,
      name: result[1] as String?,
      rssi: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeerInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(peerId, other.peerId) && _deepEquals(name, other.name) && _deepEquals(rssi, other.rssi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

sealed class TransportEvent {
}

class AdapterStateEvent extends TransportEvent {
  AdapterStateEvent({
    required this.state,
  });

  BleAdapterState state;

  List<Object?> _toList() {
    return <Object?>[
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static AdapterStateEvent decode(Object result) {
    result as List<Object?>;
    return AdapterStateEvent(
      state: result[0]! as BleAdapterState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdapterStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PeerDiscoveredEvent extends TransportEvent {
  PeerDiscoveredEvent({
    required this.peer,
  });

  PeerInfo peer;

  List<Object?> _toList() {
    return <Object?>[
      peer,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeerDiscoveredEvent decode(Object result) {
    result as List<Object?>;
    return PeerDiscoveredEvent(
      peer: result[0]! as PeerInfo,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeerDiscoveredEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(peer, other.peer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PeerConnectionEvent extends TransportEvent {
  PeerConnectionEvent({
    required this.peerId,
    required this.state,
  });

  String peerId;

  PeerConnectionState state;

  List<Object?> _toList() {
    return <Object?>[
      peerId,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeerConnectionEvent decode(Object result) {
    result as List<Object?>;
    return PeerConnectionEvent(
      peerId: result[0]! as String,
      state: result[1]! as PeerConnectionState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeerConnectionEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(peerId, other.peerId) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A fully reassembled inbound envelope (still signed + boxed — Dart decrypts).
class EnvelopeReceivedEvent extends TransportEvent {
  EnvelopeReceivedEvent({
    required this.peerId,
    required this.envelope,
    required this.receivedAtMs,
  });

  String peerId;

  Uint8List envelope;

  int receivedAtMs;

  List<Object?> _toList() {
    return <Object?>[
      peerId,
      envelope,
      receivedAtMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static EnvelopeReceivedEvent decode(Object result) {
    result as List<Object?>;
    return EnvelopeReceivedEvent(
      peerId: result[0]! as String,
      envelope: result[1]! as Uint8List,
      receivedAtMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EnvelopeReceivedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(peerId, other.peerId) && _deepEquals(envelope, other.envelope) && _deepEquals(receivedAtMs, other.receivedAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BleAdapterState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PeerConnectionState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is TransportConfig) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PeerInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AdapterStateEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PeerDiscoveredEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PeerConnectionEvent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is EnvelopeReceivedEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleAdapterState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PeerConnectionState.values[value];
      case 131:
        return TransportConfig.decode(readValue(buffer)!);
      case 132:
        return PeerInfo.decode(readValue(buffer)!);
      case 133:
        return AdapterStateEvent.decode(readValue(buffer)!);
      case 134:
        return PeerDiscoveredEvent.decode(readValue(buffer)!);
      case 135:
        return PeerConnectionEvent.decode(readValue(buffer)!);
      case 136:
        return EnvelopeReceivedEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class TransportHostApi {
  /// Constructor for [TransportHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TransportHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Initialise both CB managers with restore identifiers. Idempotent.
  Future<void> configure(TransportConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startAdvertising() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.startAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopAdvertising() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.stopAdvertising$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startScanning() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.startScanning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopScanning() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.stopScanning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> connect(String peerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect(String peerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Fragments [envelope] (START/CONTINUE/END) and writes it to [peerId].
  /// Returns true if the write was dispatched (not an end-to-end ACK — that is
  /// an application-layer envelope handled in Dart).
  Future<bool> sendEnvelope(String peerId, Uint8List envelope) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.sendEnvelope$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[peerId, envelope]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<List<String>> connectedPeers() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.connectedPeers$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Filesystem path of the App Group shared "inbox" directory where the native
  /// transport drops inbound envelope files during background wakes (when Dart
  /// is not running). Dart drains + deletes these on launch/resume. Returns
  /// null if no shared container is available.
  Future<String?> inboxDirectoryPath() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.inboxDirectoryPath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// Caches a human label for a peer identity (Ed25519 public key, hex) so the
  /// native side can name the sender in background local notifications, when
  /// Dart isn't running to do it. Persisted in the App Group UserDefaults.
  Future<void> cachePeerName(String identityHex, String name) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stonechat.TransportHostApi.cachePeerName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[identityHex, name]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

Stream<TransportEvent> streamTransportEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamTransportEventsChannel =
      EventChannel('dev.flutter.pigeon.stonechat.TransportStreamApi.streamTransportEvents$instanceName', pigeonMethodCodec);
  return streamTransportEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as TransportEvent;
  });
}
    
