// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsTransportApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashTransportApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsTransportApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsTransportApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsTransportApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsTransportApi(lhsKey, rhsKey) {
          if deepEqualsTransportApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsTransportApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashTransportApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashTransportApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashTransportApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashTransportApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashTransportApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashTransportApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Mirror of `CBManagerState`.
enum BleAdapterState: Int {
  case unknown = 0
  case resetting = 1
  case unsupported = 2
  case unauthorized = 3
  case poweredOff = 4
  case poweredOn = 5
}

/// Lifecycle of a single peer link.
enum PeerConnectionState: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case disconnecting = 3
}

/// One-time configuration handed to the native transport on startup.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TransportConfig: Hashable {
  /// Custom 128-bit GATT service UUID advertised + scanned for.
  var serviceUuid: String
  /// Single bidirectional write/notify characteristic UUID.
  var characteristicUuid: String
  /// Short name surfaced to the peer in the hello/identity handshake.
  var displayName: String
  /// `CBCentralManagerOptionRestoreIdentifierKey` value.
  var centralRestoreIdentifier: String
  /// `CBPeripheralManagerOptionRestoreIdentifierKey` value.
  var peripheralRestoreIdentifier: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TransportConfig? {
    let serviceUuid = pigeonVar_list[0] as! String
    let characteristicUuid = pigeonVar_list[1] as! String
    let displayName = pigeonVar_list[2] as! String
    let centralRestoreIdentifier = pigeonVar_list[3] as! String
    let peripheralRestoreIdentifier = pigeonVar_list[4] as! String

    return TransportConfig(
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      displayName: displayName,
      centralRestoreIdentifier: centralRestoreIdentifier,
      peripheralRestoreIdentifier: peripheralRestoreIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      characteristicUuid,
      displayName,
      centralRestoreIdentifier,
      peripheralRestoreIdentifier,
    ]
  }
  static func == (lhs: TransportConfig, rhs: TransportConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransportApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsTransportApi(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsTransportApi(lhs.displayName, rhs.displayName) && deepEqualsTransportApi(lhs.centralRestoreIdentifier, rhs.centralRestoreIdentifier) && deepEqualsTransportApi(lhs.peripheralRestoreIdentifier, rhs.peripheralRestoreIdentifier)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TransportConfig")
    deepHashTransportApi(value: serviceUuid, hasher: &hasher)
    deepHashTransportApi(value: characteristicUuid, hasher: &hasher)
    deepHashTransportApi(value: displayName, hasher: &hasher)
    deepHashTransportApi(value: centralRestoreIdentifier, hasher: &hasher)
    deepHashTransportApi(value: peripheralRestoreIdentifier, hasher: &hasher)
  }
}

/// A peer surfaced by a scan match.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PeerInfo: Hashable {
  /// Stable opaque identifier for the discovered peripheral (CBPeripheral
  /// identifier UUID string). Not the cryptographic identity — that arrives
  /// inside the first signed envelope.
  var peerId: String
  var name: String? = nil
  var rssi: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeerInfo? {
    let peerId = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi = pigeonVar_list[2] as! Int64

    return PeerInfo(
      peerId: peerId,
      name: name,
      rssi: rssi
    )
  }
  func toList() -> [Any?] {
    return [
      peerId,
      name,
      rssi,
    ]
  }
  static func == (lhs: PeerInfo, rhs: PeerInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransportApi(lhs.peerId, rhs.peerId) && deepEqualsTransportApi(lhs.name, rhs.name) && deepEqualsTransportApi(lhs.rssi, rhs.rssi)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeerInfo")
    deepHashTransportApi(value: peerId, hasher: &hasher)
    deepHashTransportApi(value: name, hasher: &hasher)
    deepHashTransportApi(value: rssi, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol TransportEvent {

}

/// Generated class from Pigeon that represents data sent in messages.
struct AdapterStateEvent: TransportEvent {
  var state: BleAdapterState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdapterStateEvent? {
    let state = pigeonVar_list[0] as! BleAdapterState

    return AdapterStateEvent(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
  static func == (lhs: AdapterStateEvent, rhs: AdapterStateEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransportApi(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AdapterStateEvent")
    deepHashTransportApi(value: state, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PeerDiscoveredEvent: TransportEvent {
  var peer: PeerInfo


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeerDiscoveredEvent? {
    let peer = pigeonVar_list[0] as! PeerInfo

    return PeerDiscoveredEvent(
      peer: peer
    )
  }
  func toList() -> [Any?] {
    return [
      peer
    ]
  }
  static func == (lhs: PeerDiscoveredEvent, rhs: PeerDiscoveredEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransportApi(lhs.peer, rhs.peer)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeerDiscoveredEvent")
    deepHashTransportApi(value: peer, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PeerConnectionEvent: TransportEvent {
  var peerId: String
  var state: PeerConnectionState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeerConnectionEvent? {
    let peerId = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! PeerConnectionState

    return PeerConnectionEvent(
      peerId: peerId,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      peerId,
      state,
    ]
  }
  static func == (lhs: PeerConnectionEvent, rhs: PeerConnectionEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransportApi(lhs.peerId, rhs.peerId) && deepEqualsTransportApi(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PeerConnectionEvent")
    deepHashTransportApi(value: peerId, hasher: &hasher)
    deepHashTransportApi(value: state, hasher: &hasher)
  }
}

/// A fully reassembled inbound envelope (still signed + boxed — Dart decrypts).
///
/// Generated class from Pigeon that represents data sent in messages.
struct EnvelopeReceivedEvent: TransportEvent {
  var peerId: String
  var envelope: FlutterStandardTypedData
  var receivedAtMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EnvelopeReceivedEvent? {
    let peerId = pigeonVar_list[0] as! String
    let envelope = pigeonVar_list[1] as! FlutterStandardTypedData
    let receivedAtMs = pigeonVar_list[2] as! Int64

    return EnvelopeReceivedEvent(
      peerId: peerId,
      envelope: envelope,
      receivedAtMs: receivedAtMs
    )
  }
  func toList() -> [Any?] {
    return [
      peerId,
      envelope,
      receivedAtMs,
    ]
  }
  static func == (lhs: EnvelopeReceivedEvent, rhs: EnvelopeReceivedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransportApi(lhs.peerId, rhs.peerId) && deepEqualsTransportApi(lhs.envelope, rhs.envelope) && deepEqualsTransportApi(lhs.receivedAtMs, rhs.receivedAtMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EnvelopeReceivedEvent")
    deepHashTransportApi(value: peerId, hasher: &hasher)
    deepHashTransportApi(value: envelope, hasher: &hasher)
    deepHashTransportApi(value: receivedAtMs, hasher: &hasher)
  }
}

private class TransportApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleAdapterState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PeerConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return TransportConfig.fromList(self.readValue() as! [Any?])
    case 132:
      return PeerInfo.fromList(self.readValue() as! [Any?])
    case 133:
      return AdapterStateEvent.fromList(self.readValue() as! [Any?])
    case 134:
      return PeerDiscoveredEvent.fromList(self.readValue() as! [Any?])
    case 135:
      return PeerConnectionEvent.fromList(self.readValue() as! [Any?])
    case 136:
      return EnvelopeReceivedEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TransportApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BleAdapterState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PeerConnectionState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? TransportConfig {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PeerInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AdapterStateEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PeerDiscoveredEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PeerConnectionEvent {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? EnvelopeReceivedEvent {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TransportApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TransportApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TransportApiPigeonCodecWriter(data: data)
  }
}

class TransportApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TransportApiPigeonCodec(readerWriter: TransportApiPigeonCodecReaderWriter())
}

var transportApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: TransportApiPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TransportHostApi {
  /// Initialise both CB managers with restore identifiers. Idempotent.
  func configure(config: TransportConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func startAdvertising() throws
  func stopAdvertising() throws
  func startScanning() throws
  func stopScanning() throws
  func connect(peerId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnect(peerId: String) throws
  /// Fragments [envelope] (START/CONTINUE/END) and writes it to [peerId].
  /// Returns true if the write was dispatched (not an end-to-end ACK — that is
  /// an application-layer envelope handled in Dart).
  func sendEnvelope(peerId: String, envelope: FlutterStandardTypedData, completion: @escaping (Result<Bool, Error>) -> Void)
  func connectedPeers() throws -> [String]
  /// Filesystem path of the App Group shared "inbox" directory where the native
  /// transport drops inbound envelope files during background wakes (when Dart
  /// is not running). Dart drains + deletes these on launch/resume. Returns
  /// null if no shared container is available.
  func inboxDirectoryPath() throws -> String?
  /// Caches a human label for a peer identity (Ed25519 public key, hex) so the
  /// native side can name the sender in background local notifications, when
  /// Dart isn't running to do it. Persisted in the App Group UserDefaults.
  func cachePeerName(identityHex: String, name: String) throws
  /// The APNs device token (hex) once the OS has handed it to us, or null if not
  /// yet available / push isn't provisioned. Dart registers it with the relay so
  /// relayed messages can wake this device.
  func pushToken() throws -> String?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TransportHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TransportApiPigeonCodec.shared }
  /// Sets up an instance of `TransportHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TransportHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialise both CB managers with restore identifiers. Idempotent.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! TransportConfig
        api.configure(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let startAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.startAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAdvertisingChannel.setMessageHandler { _, reply in
        do {
          try api.startAdvertising()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAdvertisingChannel.setMessageHandler(nil)
    }
    let stopAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.stopAdvertising\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAdvertisingChannel.setMessageHandler { _, reply in
        do {
          try api.stopAdvertising()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopAdvertisingChannel.setMessageHandler(nil)
    }
    let startScanningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.startScanning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanningChannel.setMessageHandler { _, reply in
        do {
          try api.startScanning()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanningChannel.setMessageHandler(nil)
    }
    let stopScanningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.stopScanning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanningChannel.setMessageHandler { _, reply in
        do {
          try api.stopScanning()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanningChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peerIdArg = args[0] as! String
        api.connect(peerId: peerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peerIdArg = args[0] as! String
        do {
          try api.disconnect(peerId: peerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    /// Fragments [envelope] (START/CONTINUE/END) and writes it to [peerId].
    /// Returns true if the write was dispatched (not an end-to-end ACK — that is
    /// an application-layer envelope handled in Dart).
    let sendEnvelopeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.sendEnvelope\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendEnvelopeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let peerIdArg = args[0] as! String
        let envelopeArg = args[1] as! FlutterStandardTypedData
        api.sendEnvelope(peerId: peerIdArg, envelope: envelopeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendEnvelopeChannel.setMessageHandler(nil)
    }
    let connectedPeersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.connectedPeers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectedPeersChannel.setMessageHandler { _, reply in
        do {
          let result = try api.connectedPeers()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectedPeersChannel.setMessageHandler(nil)
    }
    /// Filesystem path of the App Group shared "inbox" directory where the native
    /// transport drops inbound envelope files during background wakes (when Dart
    /// is not running). Dart drains + deletes these on launch/resume. Returns
    /// null if no shared container is available.
    let inboxDirectoryPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.inboxDirectoryPath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      inboxDirectoryPathChannel.setMessageHandler { _, reply in
        do {
          let result = try api.inboxDirectoryPath()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      inboxDirectoryPathChannel.setMessageHandler(nil)
    }
    /// Caches a human label for a peer identity (Ed25519 public key, hex) so the
    /// native side can name the sender in background local notifications, when
    /// Dart isn't running to do it. Persisted in the App Group UserDefaults.
    let cachePeerNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.cachePeerName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cachePeerNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identityHexArg = args[0] as! String
        let nameArg = args[1] as! String
        do {
          try api.cachePeerName(identityHex: identityHexArg, name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cachePeerNameChannel.setMessageHandler(nil)
    }
    /// The APNs device token (hex) once the OS has handed it to us, or null if not
    /// yet available / push isn't provisioned. Dart registers it with the relay so
    /// relayed messages can wake this device.
    let pushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stonechat.TransportHostApi.pushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pushTokenChannel.setMessageHandler { _, reply in
        do {
          let result = try api.pushToken()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pushTokenChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class StreamTransportEventsStreamHandler: PigeonEventChannelWrapper<TransportEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamTransportEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.stonechat.TransportStreamApi.streamTransportEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<TransportEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: transportApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
